"""empty message

Revision ID: 0c8db1bb84fb
Revises: f85b7b957784
Create Date: 2024-02-01 14:12:48.146651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_trigger import PGTrigger
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '0c8db1bb84fb'
down_revision: Union[str, None] = 'f85b7b957784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_books_check_authors_trigger = PGTrigger(
        schema="public",
        signature="check_authors_trigger",
        on_entity="public.books",
        is_constraint=False,
        definition='BEFORE INSERT ON public.books\n    FOR EACH ROW EXECUTE FUNCTION before_insert_book_check()'
    )
    op.create_entity(public_books_check_authors_trigger)

    public_book_author_association_check_authors_trigger = PGTrigger(
        schema="public",
        signature="check_authors_trigger",
        on_entity="public.book_author_association",
        is_constraint=False,
        definition='BEFORE INSERT ON public.book_author_association FOR EACH ROW EXECUTE FUNCTION before_insert_book_check()'
    )
    op.drop_entity(public_book_author_association_check_authors_trigger)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_book_author_association_check_authors_trigger = PGTrigger(
        schema="public",
        signature="check_authors_trigger",
        on_entity="public.book_author_association",
        is_constraint=False,
        definition='BEFORE INSERT ON public.book_author_association FOR EACH ROW EXECUTE FUNCTION before_insert_book_check()'
    )
    op.create_entity(public_book_author_association_check_authors_trigger)

    public_books_check_authors_trigger = PGTrigger(
        schema="public",
        signature="check_authors_trigger",
        on_entity="public.books",
        is_constraint=False,
        definition='BEFORE INSERT ON public.books\n    FOR EACH ROW EXECUTE FUNCTION before_insert_book_check()'
    )
    op.drop_entity(public_books_check_authors_trigger)

    # ### end Alembic commands ###
