"""add_unique_constraint_to_authors

Revision ID: 3abe4679e45f
Revises: 5b3b0dea88f3
Create Date: 2024-02-01 20:56:13.737123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3abe4679e45f'
down_revision: Union[str, None] = '5b3b0dea88f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.create_unique_constraint("uq_author_name_surname", "authors", ["author_name", "author_surname"])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
