"""create authors & books tables

Revision ID: 63f9da1020ec
Revises: 
Create Date: 2023-12-31 23:02:00.392849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f9da1020ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_name', sa.String(length=25), nullable=False),
    sa.Column('author_surname', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_authors_author_id'), 'authors', ['author_id'], unique=True)
    op.create_table('books',
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.Column('book_title', sa.String(length=50), nullable=False),
    sa.Column('book_amount', sa.SmallInteger(), nullable=False),
    sa.Column('book_description', sa.Text(), nullable=False),
    sa.Column('book_price', sa.Float(), nullable=False),
    sa.CheckConstraint('book_amount >= 0', name='CHK_book_amount_not_negative'),
    sa.CheckConstraint('book_price > 0.0', name='CHK_book_price_more_than_zero'),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_books_book_title'), 'books', ['book_title'], unique=True)
    op.create_table('book_author_association',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.author_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('author_id', 'book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_author_association')
    op.drop_index(op.f('ix_books_book_title'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_authors_author_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
